package BubbleTank;

public interface Constants {
  static final int WAIT_TIME = 10;
  static final int INFO_PANEL_SIZE = 60;
  static final int SHIFT_X_BULLET = 10;
  static final int SHIFT_Y_BULLET = 2;
  static final int MENU_WIDTH = 400;
  static final int MENU_HEIDTH = 700;
  static final int LMIN = 1;
  static final int LMAX = 14;
  static final int SPEED_1 = 5;
  static final int HEALTH_1 = 1;
  static final int RAD_1 = 20;
  static final int SPEED_2 = 4;
  static final int HEALTH_2 = 3;
  static final int RAD_2 = 40;
  static final int SPEED_3 = 3;
  static final int HEALTH_3 = 6;
  static final int RAD_3 = 60;
  static final int WAVEMULTIPLIER = 5;
  static final int WAVE_1 = 5;
  static final int WAVE_2 = 10;
  static final int WAVE_3 = 15;
  static final int RANK_1 = 1;
  static final int RANK_2 = 2;
  static final int RANK_3 = 3;
  static final int TYPE = 1;
  static final double TRUE_WAY = 1.0;
  static final double FALSE_WAY = 0.0;
  static final int BUTTON_WIDTH = 200;
  static final int BUTTON_HEIDTH = 100;
  static final int OVER_WIDTH = 300;
  static final int OVER_HEIDTH = 300;
  static final int PAUSE_WIDTH = 300;
  static final int PAUSE_HEIDTH = 150;
  static final int YAREA_25 = 25;
  static final int YAREA_15 = 15;
  static final int CIRCLE = 360;
  static final String BEST_GAME = "E:/BestGame";
  static final String WORST_GAME = "E:/WorstGame";
  final static String FILENAME = "E:/replays/";
  final static String NOTATION_FILENAME = "E:/notations/";
}